#!/bin/bash

run() {
    if ! pgrep -f "$1"; then
        "$@"&
    fi
}

run lxsession
run picom
run nm-applet
run volumeicon
run emacs --daemon
run nitrogen --restore
run mpv --no-video ~/Music/startup.mp3
